spring.application.name=banking-app
spring.datasource.url=jdbc:mysql://localhost:3306/smartdata
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# Enable multi datasource to persist read-model snapshots to banking_read_db
multi.datasource.enabled=true

app.read-datasource.url=jdbc:mysql://localhost:3306/banking_read_db
app.read-datasource.username=root
app.read-datasource.password=root
app.read-datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8081